--- 
- hosts: all 
  gather_facts: false 
 
  tasks: 
	- name: Get CPU usage 
	  shell: "top -b -n 1" 
	  register: top 
 
	- name: Set CPU usage facts 
	  set_fact: 
			user_cpu: "{{top.stdout_lines[2].split()[1]}}" 
			system_cpu: "{{top.stdout_lines[2].split()[3]}}" 
 
	- name: Output CPU usage facts 
	  debug: 
			msg: 
			  - "User CPU usage: {{user_cpu}}" 
			  - "System CPU usage: {{system_cpu}}"





        - name: Trigger emails to Team
    mail:
      host: smtp.gmail.com
      port: 587
      subtype: html
      username: kadurunarendra@gmail.com
      password: "{{ gmail_pass }}"
      to: kadurunarendra@gmail.com
      from: kadurunarendra@gmail.com
      attach: /home/devops/shellscripts/metric-log.txt
      subject: Ansible-report for monitoring CPU and Memory Usage
      body: 'Monitoring has been successfully provisioned.'
    delegate_to: localhost